version: 2

models:

  # ── Transform ─────────────────────────────────────────────

  - name: historical_transform
    description: "Base transform layer with derived columns"
    columns:
      - name: city
        data_tests:
          - not_null

      - name: date
        data_tests:
          - not_null
    tests:
    - dbt_utils.unique_combination_of_columns:
        combination_of_columns: [city, date]

  - name: forecasting_transform
    description: "Base transform layer with derived columns"
    columns:
      - name: city
        data_tests:
          - not_null

      - name: date
        data_tests:
          - not_null

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [city, date]

  # ── Analytics ─────────────────────────────────────────────

  - name: historical_analytics
    description: "histrorical trends"
    columns:
      - name: city
        data_tests:
          - not_null

      - name: date
        data_tests:
          - not_null

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [city, date]

  - name: forecasting_analytics
    description: "forecasting 1 year trends"
    columns:
      - name: city
        data_tests:
          - not_null

      - name: date
        data_tests:
          - not_null

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [city, date]

  - name: realtime_analytics
    description: "real time analytics"
    columns:
      - name: city
        data_tests:
          - not_null

      - name: date
        data_tests:
          - not_null

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [city, date]